from __future__ import annotations

import math
from typing import Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


class FourierPositionEncoding(nn.Module):
    """Deterministic 2-D Fourier positional encoding in [-1, 1].

    It is intentionally parameter-free so that the spatial identity does not
    collapse during early fine-tuning and can be regenerated by the extractor.
    """

    def __init__(self, num_bands: int = 4, include_xy: bool = True):
        super().__init__()
        self.num_bands = int(num_bands)
        self.include_xy = bool(include_xy)

    @property
    def out_channels(self) -> int:
        return (2 if self.include_xy else 0) + 4 * self.num_bands

    def forward(self, batch: int, height: int, width: int, device, dtype) -> torch.Tensor:
        y = torch.linspace(-1.0, 1.0, height, device=device, dtype=dtype)
        x = torch.linspace(-1.0, 1.0, width, device=device, dtype=dtype)
        yy, xx = torch.meshgrid(y, x, indexing="ij")
        feats = []
        if self.include_xy:
            feats.extend([xx, yy])
        for i in range(self.num_bands):
            freq = (2.0 ** i) * math.pi
            feats.extend([
                torch.sin(freq * xx),
                torch.cos(freq * xx),
                torch.sin(freq * yy),
                torch.cos(freq * yy),
            ])
        pos = torch.stack(feats, dim=0).unsqueeze(0)
        return pos.expand(batch, -1, -1, -1)


class PositionCodeField(nn.Module):
    """Generate a local spatial code C(u,v) conditioned on bits and coordinates."""

    def __init__(
        self,
        bit_dim: int = 64,
        code_dim: int = 8,
        hidden_dim: int = 64,
        fourier_bands: int = 4,
    ):
        super().__init__()
        self.bit_dim = bit_dim
        self.code_dim = code_dim
        self.pos = FourierPositionEncoding(fourier_bands)
        self.bit_proj = nn.Sequential(
            nn.Linear(bit_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )
        self.pos_proj = nn.Sequential(
            nn.Conv2d(self.pos.out_channels, hidden_dim, 1),
            nn.SiLU(),
        )
        self.fuse = nn.Sequential(
            nn.Conv2d(hidden_dim * 2, hidden_dim, 1),
            nn.SiLU(),
            nn.Conv2d(hidden_dim, code_dim, 1),
            nn.Tanh(),
        )

    def forward(self, bits: torch.Tensor, spatial_size: Tuple[int, int]) -> torch.Tensor:
        if bits.ndim != 2:
            raise ValueError(f"bits must be [B, K], got {tuple(bits.shape)}")
        b = bits.shape[0]
        h, w = spatial_size
        msg = self.bit_proj(bits).unsqueeze(-1).unsqueeze(-1).expand(-1, -1, h, w)
        pos = self.pos(b, h, w, bits.device, bits.dtype)
        pos = self.pos_proj(pos)
        return self.fuse(torch.cat([msg, pos], dim=1))


class PositionBoundSpatialInjection(nn.Module):
    """Drop-in replacement for GenPTW Spatial Fusion.

    The original global watermark latent is retained for checkpoint continuity,
    while a low-dimensional position-bound code field provides local identity.
    A small learned residual scale reduces the risk of visual-quality collapse.
    """

    def __init__(
        self,
        wm_latent_dim: int,
        z_channels: int = 256,
        bit_dim: int = 64,
        code_dim: int = 8,
        hidden_dim: int = 64,
        fourier_bands: int = 4,
        init_logit: float = -4.0,
    ):
        super().__init__()
        self.z_channels = z_channels
        self.global_proj = nn.Linear(wm_latent_dim, z_channels)
        self.code_generator = PositionCodeField(
            bit_dim=bit_dim,
            code_dim=code_dim,
            hidden_dim=hidden_dim,
            fourier_bands=fourier_bands,
        )
        in_ch = z_channels + z_channels + code_dim
        self.gate = nn.Sequential(nn.Conv2d(in_ch, z_channels, 1), nn.Sigmoid())
        self.residual = nn.Sequential(
            nn.Conv2d(in_ch, z_channels, 3, padding=1),
            nn.SiLU(),
            nn.Conv2d(z_channels, z_channels, 3, padding=1),
        )
        self.alpha_logit = nn.Parameter(torch.tensor(float(init_logit)))

        # Start the final residual conv near zero. This preserves upstream
        # generation quality before fine-tuning.
        nn.init.zeros_(self.residual[-1].weight)
        if self.residual[-1].bias is not None:
            nn.init.zeros_(self.residual[-1].bias)

    def forward(
        self,
        z: torch.Tensor,
        wm_latent: torch.Tensor,
        bits: torch.Tensor,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        b, _, h, w = z.shape
        global_feat = self.global_proj(wm_latent.reshape(b, -1))
        global_feat = global_feat.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, h, w)
        code = self.code_generator(bits, (h, w))
        x = torch.cat([z, global_feat, code], dim=1)
        delta = self.gate(x) * self.residual(x)
        alpha = torch.sigmoid(self.alpha_logit)
        return z + alpha * delta, code

    @torch.no_grad()
    def expected_code(self, bits: torch.Tensor, spatial_size: Tuple[int, int]) -> torch.Tensor:
        return self.code_generator(bits, spatial_size)
